# Generated by Django 4.1 on 2022-08-24 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[(1, 'MANAGER'), (2, 'STAFF'), (3, 'EMPLOYEE')], default=1, max_length=50),
        ),
    ]
