# Generated by Django 4.1 on 2022-08-26 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_department'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
