# Generated by Django 4.1 on 2022-08-26 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_employee_leave'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee_leave',
            old_name='date',
            new_name='data',
        ),
    ]
