# Generated by Django 4.1 on 2022-08-28 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_employee_notification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee_notification',
            old_name='staff_id',
            new_name='employee_id',
        ),
    ]
