# Generated by Django 4.1 on 2022-08-28 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_staff'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Staff',
        ),
    ]
