# Generated by Django 4.1 on 2022-08-29 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='department_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.department'),
        ),
    ]
