# Generated by Django 4.1 on 2022-09-03 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_register_as_smes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register_as_smes',
            name='proposal',
        ),
    ]
