# Generated by Django 4.1 on 2022-09-04 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_remove_register_as_smes_field_fieldofstudies'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FieldOfStudies',
        ),
    ]
