# Generated by Django 4.1 on 2022-09-04 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_register_as_smes_field'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Register_as_smes',
        ),
    ]
