# Generated by Django 4.1 on 2022-09-07 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_alter_staff_feedback_staff_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register_as_startUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campany', models.CharField(max_length=100)),
                ('campany_type', models.TextField()),
                ('first_name', models.CharField(max_length=100)),
                ('father_name', models.CharField(max_length=100)),
                ('grand_father_name', models.CharField(max_length=100)),
                ('nationality', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('zone', models.CharField(max_length=100)),
                ('kebele', models.CharField(max_length=100)),
                ('house_number', models.CharField(max_length=100)),
                ('p_o_box', models.CharField(max_length=100)),
                ('fax', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('capital', models.CharField(max_length=100)),
                ('tin', models.CharField(max_length=100)),
                ('registasion_date', models.DateField()),
                ('vat_no', models.CharField(max_length=100)),
                ('about_title', models.TextField()),
                ('field', models.TextField()),
                ('proposal', models.FileField(upload_to='file')),
            ],
        ),
    ]
